# Generated by Django 4.2.6 on 2023-10-31 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.IntegerField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=20)),
                ('customerTin', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=5)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stockId', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('itemName', models.CharField(max_length=15)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierId', models.IntegerField(primary_key=True, serialize=False)),
                ('supplierName', models.CharField(max_length=20)),
                ('supplierTin', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('saleId', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchaseId', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.supplier')),
            ],
        ),
    ]
