# Generated by Django 4.2.6 on 2023-10-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
