# Generated by Django 4.2.6 on 2023-10-31 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0002_remove_stock_quantity_alter_product_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='itemName',
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StockApp.product'),
        ),
    ]
